apiVersion: v1
kind: Pod
metadata:
  labels:
    app: aitriage-to-loki
  name: aitriage-to-loki
spec:
  containers:
  - image: docker.io/grafana/loki:2.4.2
    name: loki
    ports:
    - hostPort: 3100
    volumeMounts:
    - mountPath: /etc/loki:Z
      name: loki-config
    - mountPath: /srv/loki:z
      name: loki-data
    securityContext:
      runAsUser: 0
  - image: docker.io/grafana/grafana:8.4.5
    name: grafana
    ports:
    - hostPort: 3000
    volumeMounts:
    - mountPath: /etc/grafana:Z
      name: grafana-config
  - image: docker.io/grafana/promtail:2.4.1
    name: promtail
    volumeMounts:
    - mountPath: /etc/promtail:Z
      name: promtail-config
    - mountPath: /run/promtail:Z
      name: promtail-data
    - mountPath: /var/log:z
      name: log-data
  volumes:
  - hostPath:
      path: podman/loki
      type: Directory
    name: loki-config
  - hostPath:
      path: podman/promtail
      type: Directory
    name: promtail-config
  - hostPath:
      path: podman/grafana
      type: Directory
    name: grafana-config
  - hostPath:
      path: foo/promtail-data
      type: Directory
    name: promtail-data
  - hostPath:
      path: foo/loki-data
      type: Directory
    name: loki-data
  - hostPath:
      path: foo
      type: Directory
    name: log-data
